# Generated by Django 5.2.5 on 2025-09-23 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Account type ')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Branch Name')),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, default='N/A', max_length=100, null=True)),
                ('contact', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_date', models.DateField(auto_now=True)),
                ('pin', models.CharField(max_length=20)),
                ('balance', models.IntegerField()),
                ('account_status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('S', 'Suspended')], max_length=2)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ar_bank.account_type')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ar_bank.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ar_bank.customer')),
            ],
        ),
    ]
