# Generated by Django 5.2.5 on 2025-10-06 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar_bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('employee_position', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('deposit_amount', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ar_bank.account')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ar_bank.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.IntegerField(verbose_name='transaction_amount')),
                ('transaction_type', models.CharField(max_length=30)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ar_bank.account')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ar_bank.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('transfer_amount', models.IntegerField()),
                ('receivers_account', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ar_bank.account')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ar_bank.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('withdraw_amount', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ar_bank.account')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ar_bank.employee')),
            ],
        ),
    ]
