# Generated by Django 5.2.5 on 2025-10-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar_bank', '0002_employee_deposit_transaction_transfer_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_number',
            field=models.CharField(default='0000', max_length=30),
        ),
    ]
