# Generated by Django 5.2.5 on 2025-10-26 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar_bank', '0003_account_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to='ar_bank.account'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='receivers_account',
            field=models.ForeignKey(default='0000', on_delete=django.db.models.deletion.CASCADE, related_name='received_transfers', to='ar_bank.account'),
        ),
    ]
