# Generated by Django 5.2.5 on 2025-10-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar_bank', '0004_alter_transfer_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('D', 'Deposi'), ('W', 'Withdraw'), ('T', 'Transfer')], max_length=2),
        ),
    ]
