# Generated by Django 5.2.5 on 2025-10-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar_bank', '0005_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('D', 'Deposit'), ('W', 'Withdraw'), ('T', 'Transfer')], max_length=2),
        ),
    ]
