# Generated by Django 5.2.5 on 2025-11-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar_bank', '0006_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='opening_date',
            field=models.DateField(),
        ),
    ]
